### ISSUE TITLE
java.lang.classcastexception: com.bea.security.saml2.providers.registry.webssoidppartnerimpl cannot be cast to com.bea.security.saml2.providers.registry.webssopartner

### ISSUE THREAD

**Issue by lopesrohan1988** [cerndb/wls-cern-sso#1]
Got this error while running the SAMLSLO on weblogic. 
I removed the wls-api.jar from WEB-INF/lib folder and it worked.
This is because the class is loaded by the weblogic classloader.

**Comment by lurodrig** [comment]
Thank you very much for your feedback and sorry for the loooooong delay in my response. The notification email got buried in my inbox folder :(

Yes, such libraries are used just in runtime. Now that oracle has a maven repo you could think in use them and mark them as compile.

Cheers,

Luis
