### ISSUE TITLE
encrypted assertions

### ISSUE THREAD

**Issue by joeblack81** [cerndb/wls-cern-sso#2]
Dear Luis, 
I have successfully  implemented SAML2 ,SP with Weblogic 12c using biemond tutorial and your class mapper.
I connect to external Idp, and been able to consume the SAML Assertions only if the Idp sends the assertions non encrypted. 
but if the Idp sends  encrypted assertions , I got ( array out of bounds exception ).
Can you help me with this issue? 
Best Regards

**Comment by lurodrig** [comment]
Sorry for the incredible delay in my answer, almost 2 years, amazing! Unfortunately in our setup we do not use encrypted assertions, and I do think that WebLogic does not support them.

In the other hand I know that shibboleth support them out-of-the-box, perhaps you could give it a try.

Sorry again and best regards,

Luis
